services:
  redis: 
    image: redis
    ports:
      - '6379:6379' 
  app:
    build: 
      context: .
      args:
        - REDIS_HOST = redis
        - REDIS_PORT = 6379
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
